# This is a basic workflow to help you get started with Actions

name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Run script
        run: |
          echo "Hello World!"
          echo "Done - bye!"

